// <auto-generated />
namespace CrmBl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _09022020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09022020));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091716290_09022020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
